
use-grammars = { only = [ "janet", "typst" ] }

[language-server.deno]
command = "deno"
args = ["lsp"]
config = { deno = { enable = true } }

[language-server.typst-lsp]
command = "typst-lsp"
config = { exportPdf = "never" }

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "never", formatterMode = "typstyle" }

[[language]]
name = "janet"
scope = "source.janet"
file-types = [ "janet" ]
roots = [ "project.janet" ]

[[grammar]]
name = "janet"
source = { git = "https://github.com/GrayJack/tree-sitter-janet", rev = "1d002c23d4e952ce24a2e472d0f81ab0471ceb1b" }

[[language]]
name = "javascript"
language-servers = [
  { name = "deno" },
]

[[language]]
name = "jsx"
language-servers = [
  { name = "deno" },
]

[[language]]
name = "typescript"
language-servers = [
  { name = "deno" },
]

[[language]]
name = "tsx"
language-servers = [
  { name = "deno" },
]

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "e35aa22395fdde82bbc4b5700c324ce346dfc9e5" }
