
use-grammars = { only = [ "janet", "typst" ] }

[language-server.deno]
command = "deno"
args = ["lsp"]
config = { deno = { enable = true } }

# remove with helix 24.04
[language-server.typst-lsp]
command = "typst-lsp"

[[language]]
name = "janet"
scope = "source.janet"
file-types = [ "janet" ]
roots = [ "project.janet" ]

[[grammar]]
name = "janet"
source = { git = "https://github.com/GrayJack/tree-sitter-janet", rev = "1d002c23d4e952ce24a2e472d0f81ab0471ceb1b" }

[[language]]
name = "javascript"
language-servers = [
  { name = "deno" },
]

[[language]]
name = "typescript"
language-servers = [
  { name = "deno" },
]

# remove with helix 24.04
[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typst"
file-types = ["typst", "typ"]
roots = []
comment-token = "//"
language-servers = ["typst-lsp"]
indent = { tab-width = 2, unit = "  " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "e35aa22395fdde82bbc4b5700c324ce346dfc9e5" }
