[user]
name = "Lukas Werling"
email = "lukas@lwrl.de"

[ui]
default-command = "log"
pager = "less -FRX"
editor = "hx"

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

